version: 2.1

aliases:
  - &docker
    - image: circleci/node:erbium

  - &restore_yarn_cache
    restore_cache:
      name: Restore node_modules cache
      keys:
        - v1-node-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
        - v1-node-{{ arch }}-{{ .Branch }}-
        - v1-node-{{ arch }}-
  - &run_yarn
    run:
      name: Install Packages
      command: yarn --frozen-lockfile

jobs:
  setup:
    docker: *docker
    steps:
      - checkout
      - run:
          name: Nodejs Version
          command: node --version
      - *restore_yarn_cache
      - *run_yarn
      - save_cache:
          name: Save node_modules cache
          key: v1-node-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

  lint:
    docker: *docker
    steps:
      - checkout
      - *restore_yarn_cache
      - *run_yarn
      - run: yarn eslint
  
  build:
    docker: *docker
    steps:
      - checkout
      - *restore_yarn_cache
      - *run_yarn
      - run: yarn build

workflows:
  stable:
    jobs:
      - setup
      - lint:
          requires:
            - setup
      - build:
          requires:
            - lint
